### ISSUE TITLE
大神分身？

### ISSUE THREAD

**Issue by cocoay** [ChenYilong/CYLTableViewRowAction#1]
https://github.com/JazysYu/JZTableViewRowAction/tree/master/JZTableViewRowAction

**Comment by ChenYilong** [comment]
不是，链接里这个库没支持pod，我fork了下，方便pod。文档中已经做出了说明：https://github.com/ChenYilong/CYLTableViewRowAction/commit/c2da81e76e4acddecab9d0d4aa10d6cdee48aa1b

**Comment by cocoay** [comment]
谢谢大神回复

发自 网易邮箱大师
在2016年09月10日 22:10，微博@iOS程序犭袁 写道:

不是，链接里这个库没支持pod，我fork了下，方便pod。
